// ============================================================================
// REGIONS — the outer country of every world but the Neighborhood.
// The hand-built heart of a world is small; everything past it is generated by
// dropping prefab clusters onto a jittered ring. That is what makes the six
// outer worlds ten times the area without ten times the hand-placing.
// ============================================================================

/**
 * Scatters clusters through the ring between `inner` and `outer`. `kinds` is a weighted list of
 * { w, build(game, r, x, z) }; every cluster claims a keep-out circle, so they never grow into each
 * other, into a road, or into the hand-built middle of the world.
 */
function fillRing(game, r, { inner, outer, count, kinds, pad = 7, claim = null, skip = null, chunk = 64, range = 230 }) {
  const W = game.world, total = kinds.reduce((a, k) => a + (k.w ?? 1), 0), i2 = (inner / outer) ** 2;
  const chunks = new Map();
  const chunkFor = (x, z) => {
    const cx = Math.round(x / chunk), cz = Math.round(z / chunk), key = cx + ',' + cz;
    let c = chunks.get(key);
    if (!c) { c = new THREE.Group(); c.userData.cx = cx * chunk; c.userData.cz = cz * chunk; W.add(c); chunks.set(key, c); }
    return c;
  };
  let placed = 0;
  for (let i = 0; i < count; i++) {
    const a = r() * TAU, d = sqrt(lerp(i2, 1, r())) * outer, x = cos(a) * d, z = sin(a) * d;
    if (skip && skip(x, z)) continue;
    if (game.zones.blocked(x, z, pad)) continue;
    const c = chunkFor(x, z), before = W.children.length;
    let pick = r() * total;
    for (const k of kinds) { pick -= (k.w ?? 1); if (pick <= 0) { k.build(game, r, x, z); placed++; break; } }
    // props add themselves straight to the world; sweep the new ones into this cluster's chunk so the
    // whole chunk can be switched off in one go when it is too far away to matter
    for (let j = W.children.length - 1; j >= before; j--) c.add(W.children[j]);
    game.zones.addCircle(x, z, claim ?? pad);
  }
  const list = [...chunks.values()], far = (range + chunk) * (range + chunk);
  fillRing.lastPlaced = placed;
  return (dt, t) => { const p = game.cat.group.position; for (const c of list) c.visible = dist2(p.x, p.z, c.userData.cx, c.userData.cz) < far; };
}
/** Scatters `n` points in a blob of radius `rad` around (x,z) and calls `f` for each. */
function blob(r, x, z, rad, n, f) { for (let i = 0; i < n; i++) { const a = r() * TAU, d = sqrt(r()) * rad; f(x + cos(a) * d, z + sin(a) * d, i); } }

// ---------------------------------------------------------------- Candy Land
function makeCupcake(game, x, z, hue, r) {
  const cup = group(x, 0, z, game.world), icing = mat(new THREE.Color().setHSL(hue / 360, 0.85, 0.7), { roughness: 0.6 });
  mesh(G.cyl(2.6, 2.0, 3.0, 20), mat(0xd9a066, { roughness: 0.95 }), { y: 1.5, parent: cup });
  for (let k = 0; k < 12; k++) mesh(G.box(0.25, 3.0, 0.1), mat(0xb8843f, { roughness: 1 }), { x: cos(k / 12 * TAU) * 2.35, y: 1.5, z: sin(k / 12 * TAU) * 2.35, ry: -k / 12 * TAU, shadow: 'none', parent: cup });
  mesh(G.sphere(2.6, 18, 12), icing, { y: 3.6, sy: 0.8, parent: cup }); mesh(G.sphere(1.6, 16, 10), icing, { y: 5.1, parent: cup }); mesh(G.sphere(0.9, 14, 10), icing, { y: 6.2, parent: cup });
  mesh(G.sphere(0.4, 10, 8), mat(0xd62839, { roughness: 0.4 }), { y: 6.95, parent: cup });
  for (let k = 0; k < 40; k++) { const a = r() * TAU, e = r.range(0.2, 1.2); mesh(G.box(0.1, 0.04, 0.24), mat(r.pick([0xffffff, 0xffd54a, 0x7fd7ff, 0xff6fb5, 0x4ade80]), { roughness: 0.6 }), { x: cos(a) * 2.3 * cos(e), y: 3.6 + sin(e) * 2.1, z: sin(a) * 2.3 * cos(e), ry: a, rx: r() * PI, shadow: 'none', parent: cup }); }
  game.physics.addBox(x, 3, z, 5.2, 6, 5.2);
  return cup;
}
function makeGingerCottage(game, x, z, ry, r) {
  const gh = group(x, 0, z, game.world); gh.rotation.y = ry;
  const cookie = mat(0xc27b3a, { roughness: 0.95 }), icing = mat(0xfffdf7, { roughness: 0.35 });
  mesh(G.box(7, 4, 6), cookie, { y: 2, shadow: 'both', parent: gh });
  mesh(G.gable(6.8, 2.8, 7.6), mat(0x8a4a2a, { roughness: 0.9 }), { y: 4, ry: PI / 2, parent: gh });
  for (let k = 0; k < 8; k++) for (const s of [-1, 1]) mesh(G.sphere(0.32, 8, 6), icing, { x: -3.5 + k * 1.0, y: 4.4, z: s * 3.4, sy: 0.5, shadow: 'none', parent: gh });
  for (let k = 0; k < 9; k++) mesh(G.sphere(0.3, 10, 8), glowMat(r.pick([0xff3355, 0x4ade80, 0x64b5f6, 0xffd54a]), 0.5), { x: -3.2 + k * 0.8, y: 4.9 + abs(4 - k) * 0.45, z: 3.6 - abs(4 - k) * 0.42, shadow: 'none', parent: gh });
  mesh(G.box(1.2, 2.1, 0.16), mat(0x8a4a2a), { y: 1.05, z: 3.08, parent: gh });
  mesh(G.torus(0.7, 0.08, 6, 14, PI), icing, { y: 2.1, z: 3.12, shadow: 'none', parent: gh });
  for (const wx of [-2.2, 2.2]) { mesh(G.box(1.2, 1.2, 0.14), glowMat(0xffe082, 0.6), { x: wx, y: 2.2, z: 3.08, shadow: 'none', parent: gh }); mesh(G.torus(0.75, 0.07, 6, 14), icing, { x: wx, y: 2.2, z: 3.12, shadow: 'none', parent: gh }); }
  for (let k = 0; k < 6; k++) mesh(G.cyl(0.5, 0.65, 0.8, 12), mat(r.pick([0xff6fb5, 0x7fd7ff, 0xffd54a]), { roughness: 0.4 }), { x: -3.5 + k * 1.4, y: 0.4, z: 4.2, parent: gh });
  addRotBox(game, x, 2, z, 7.4, 4, 6.4, ry);
  return gh;
}
/** A still pool of chocolate with a wafer rim — decorative, and you can walk right up to it. */
function makeChocolatePool(game, x, z, rad, r) {
  const g = group(x, 0, z, game.world);
  const choc = mat(0x5a2d12, { roughness: 0.25, emissive: 0x2a1204, emissiveIntensity: 0.4, map: TEX.chocolate() });
  mesh(G.cyl(rad, rad, 0.1, 28), choc, { y: 0.05, shadow: 'receive', parent: g });
  mesh(G.cyl(rad + 0.6, rad + 0.8, 0.22, 28), mat(0xd9a066, { roughness: 0.95 }), { y: 0.02, shadow: 'receive', parent: g });
  for (let i = 0; i < 14; i++) { const a = i / 14 * TAU; mesh(G.cyl(0.4, 0.5, 0.5, 10), mat(r.pick([0xff6fb5, 0x7fd7ff, 0xffd54a, 0x4ade80]), { roughness: 0.4 }), { x: cos(a) * (rad + 0.9), y: 0.25, z: sin(a) * (rad + 0.9), parent: g }); }
  game.physics.addBox(x, 1.5, z, rad * 1.9, 3, rad * 1.9, { walk: false, cam: false });
  return g;
}
function candyRegion(game, U, r, inner, outer) {
  const W = game.world;
  U.push(fillRing(game, r, { inner, outer, count: 900, pad: 12, claim: 7, range: 230, skip: (x, z) => abs(z + 18) < 9, kinds: [
    { w: 4, build: (g, r, x, z) => blob(r, x, z, 7, r.int(5, 9), (cx, cz) => { const h = r.range(2.6, 4.6), c = makeCandyCane(h); c.position.set(cx, 0, cz); c.rotation.y = r() * TAU; W.add(c); g.physics.addBox(cx, h / 2, cz, 0.5, h, 0.5, { cam: false }); }) },
    { w: 3, build: (g, r, x, z) => blob(r, x, z, 8, r.int(3, 6), (cx, cz) => { const s = r.range(1.1, 2.0), l = makeLollipop(s, r.pick([330, 0, 200, 50, 280, 120]), r.range(2.6, 4.4)); l.position.set(cx, 0, cz); l.rotation.y = r() * TAU; W.add(l); g.physics.addBox(cx, 1.5, cz, 0.4, 3, 0.4, { cam: false }); }) },
    { w: 3, build: (g, r, x, z) => blob(r, x, z, 7, r.int(4, 8), (cx, cz) => { const b = makeMarshmallowBush(r); b.position.set(cx, 0, cz); W.add(b); g.physics.addBox(cx, 0.5, cz, 1.2, 1, 1.2, { cam: false }); }) },
    { w: 2, build: (g, r, x, z) => makeCupcake(g, x, z, r.pick([330, 200, 50, 120, 280, 0]), r) },
    { w: 2, build: (g, r, x, z) => makeGumdrops(g, [[x, z, 7, 22]], r) },
    { w: 1, build: (g, r, x, z) => makeGingerCottage(g, x, z, r() * TAU, r) },
    { w: 1, build: (g, r, x, z) => makeChocolatePool(g, x, z, r.range(5, 11), r) },
    { w: 1, build: (g, r, x, z) => { const d = makeDonut(r.pick([0xff6fb5, 0x7fd7ff, 0xffd54a])); const ry = r() * TAU; d.position.set(x, 0, z); d.rotation.y = ry; W.add(d); addRotBox(g, x, 1.2, z, 0.6, 2.4, 3.4, ry, { cam: false }); } },
  ] }));
  // a few more gingerbread folk out in the sweet-lands, so the far country is not empty
  for (let i = 0; i < 10; i++) {
    const a = r() * TAU, d = r.range(inner, outer * 0.85), x = cos(a) * d, z = sin(a) * d;
    const rig = makeGingerbread(); W.add(rig.group);
    game.npcs.push(new Wanderer(game, rig, { x, z, speed: r.range(0.6, 0.9), leash: 12, r: 0.4, height: 1.4, idle: [1, 3] }));
  }
}

// ---------------------------------------------------------------- Robot City
function robotRegion(game, U, r, inner, outer) {
  const W = game.world, P = game.physics;
  const pipe = mat(0x5a6470, { metalness: 0.8, roughness: 0.35 });
  const lampPost = (x, z) => { mesh(G.cyl(0.1, 0.14, 6, 8), pipe, { x, y: 3, z, parent: W }); mesh(G.box(0.6, 0.3, 0.4), glowMat(0xe8f4ff, 2), { x, y: 6, z, shadow: 'none', parent: W }); pointLight(0xcfe6ff, 40, 20, x, 5.6, z, W); P.addBox(x, 3, z, 0.3, 6, 0.3, { cam: false }); };
  U.push(fillRing(game, r, { inner, outer, count: 700, pad: 16, claim: 9, range: 240, kinds: [
    { w: 5, build: (g, r, x, z) => blob(r, x, z, 12, r.int(2, 4), (cx, cz, i) => { const w = r.range(7, 15), h = r.range(16, 58), b = makeSkyscraper(w, h, w * r.range(0.8, 1.2), floor(abs(cx + cz) + i)); b.position.set(cx, 0, cz); W.add(b); if (b.userData.update) U.push(b.userData.update); P.addBox(cx, h / 2, cz, w, h, w); }) },
    { w: 2, build: (g, r, x, z) => { flatPlane(g, 20, 20, mat(0x2a2f38, { roughness: 0.6, metalness: 0.4 }), x, z, 0, 0.015); U.push(makeConveyor(g, x, z, 12, r.chance(0.5) ? 1 : -1).userData.update); U.push(makeRobotArm(g, x + 6, z + 5).userData.update); lampPost(x - 7, z - 6); } },
    { w: 2, build: (g, r, x, z) => { const crateM = mat(0x8a6a3a, { roughness: 0.9, map: TEX.planks(30, 34) }); blob(r, x, z, 6, r.int(5, 10), (cx, cz) => { const s = r.range(0.8, 1.4); mesh(G.box(s, s, s), crateM, { x: cx, y: s / 2, z: cz, ry: r() * 0.6, parent: W }); P.addBox(cx, s / 2, cz, s, s, s, { cam: false }); }); lampPost(x + 6, z); } },
    { w: 2, build: (g, r, x, z) => { const barrelM = mat(0x2f6f9f, { metalness: 0.6, roughness: 0.4 }); blob(r, x, z, 5, r.int(4, 8), (cx, cz) => { mesh(G.cyl(0.5, 0.5, 1.2, 14), barrelM, { x: cx, y: 0.6, z: cz, parent: W }); P.addBox(cx, 0.6, cz, 1, 1.2, 1, { cam: false }); }); } },
    { w: 2, build: (g, r, x, z) => { const len = r.range(14, 30), ry = r.chance(0.5) ? PI / 2 : 0; mesh(G.cyl(0.35, 0.35, len, 12), pipe, { x, y: 3.6, z, rz: PI / 2, ry, parent: W }); for (let k = 3; k < len; k += 7) mesh(G.cyl(0.14, 0.14, 3.4, 8), pipe, { x: ry ? x : x - len / 2 + k, y: 1.9, z: ry ? z - len / 2 + k : z, parent: W }); } },
    { w: 1, build: (g, r, x, z) => { const s = makeNeonSign(r.pick(['SECTOR 9', 'CHARGE', 'OIL', 'UNIT 7', 'SCRAP', 'BOLTS']), r.pick(['#ff2d95', '#00e5ff', '#4ade80', '#ff9f43', '#ffe040']), r.range(4, 8), W); s.position.set(x, r.range(5, 9), z); s.rotation.y = r() * TAU; for (const dx of [-2, 2]) { mesh(G.cyl(0.12, 0.16, 9, 8), pipe, { x: x + dx, y: 4.5, z, parent: W }); P.addBox(x + dx, 4.5, z, 0.4, 9, 0.4, { cam: false }); } } },
    { w: 1, build: (g, r, x, z) => { U.push(makeFurnace(g, x, z, r() * TAU).userData.update); lampPost(x + 5, z + 5); } },
  ] }));
  for (let i = 0; i < 12; i++) {
    const a = r() * TAU, d = r.range(inner, outer * 0.85), x = cos(a) * d, z = sin(a) * d;
    const rig = makeRobot(); W.add(rig.group);
    game.npcs.push(new Wanderer(game, rig, { x, z, speed: r.range(0.5, 0.8), leash: 14, r: 0.42, height: 1.9, idle: [1.5, 4] }));
  }
}

// ---------------------------------------------------------------- Victorian
/**
 * A ploughed field with a hedge round it: two draw calls and a strip of instanced bushes. Farmland is
 * what keeps the country outside a Victorian town from reading as an empty parade ground.
 */
function makeField(game, x, z, r) {
  const w = r.range(26, 48), d = r.range(26, 48), ry = r() * TAU;
  const crop = r.pick([0x6f7f3e, 0x8a8a3a, 0x5f7a40, 0x9a8a4a, 0x76853f]);
  const p = flatPlane(game, w, d, mat(crop, { roughness: 1, map: groundMap(TEX.grass(), w, d, 3.2) }), x, z, ry, 0.012);
  const n = 90, hedge = new THREE.InstancedMesh(G.sphere(1, 7, 5), mat(0x2f4a28, { roughness: 1 }), n);
  const M = new THREE.Matrix4(), Q = new THREE.Quaternion(), S = new THREE.Vector3(), Pv = new THREE.Vector3(), C = new THREE.Color();
  const ca = cos(ry), sa = sin(ry);
  for (let i = 0; i < n; i++) {
    const k = i / n * 4, side = floor(k), t = (k - side) - 0.5;
    const lx = side % 2 === 0 ? t * w : (side === 1 ? w / 2 : -w / 2), lz = side % 2 === 0 ? (side === 0 ? -d / 2 : d / 2) : t * d;
    const px = x + lx * ca - lz * sa, pz = z + lx * sa + lz * ca;
    M.compose(Pv.set(px, 0.5, pz), Q, S.set(r.range(0.7, 1.1), r.range(0.5, 0.8), r.range(0.7, 1.1))); hedge.setMatrixAt(i, M);
    hedge.setColorAt(i, C.setHSL(r.range(0.24, 0.32), 0.4, r.range(0.16, 0.26)));
  }
  hedge.instanceColor.needsUpdate = true; hedge.castShadow = false; hedge.receiveShadow = true; game.world.add(hedge); worldBag.track(hedge);
  return p;
}
function victorianRegion(game, U, r, inner, outer) {
  const W = game.world, P = game.physics;
  const pave = mat(0xa8a29a, { roughness: 1, map: TEX.sidewalk() });
  const hues = [12, 8, 18, 6, 14, 10, 16, 4];
  U.push(fillRing(game, r, { inner, outer, count: 800, pad: 17, claim: 9, range: 190, kinds: [
    { w: 8, build: (g, r, x, z) => makeField(g, x, z, r) },
    { w: 4, build: (g, r, x, z) => {   // a terrace: three or four houses shoulder to shoulder behind railings
      const ry = r.pick([0, PI / 2, PI, -PI / 2]), n = r.int(3, 4), front = 1;
      for (let i = 0; i < n; i++) {
        const off = (i - (n - 1) / 2) * 8, hx = x + cos(ry) * off, hz = z - sin(ry) * off;
        const h = r.range(6.5, 9), house = makeVicHouse({ w: 7, d: 7, h, hue: hues[(i + floor(abs(x))) % hues.length], bay: r.chance(0.5) }, r);
        house.position.set(hx, 0, hz); house.rotation.y = ry; W.add(house); if (house.userData.update) U.push(house.userData.update);
        addRotBox(g, hx, h / 2, hz, 7, h, 7, ry);
        U.push(((cx, cz, top) => (dt) => { const p = g.cat.group.position; if (dist2(p.x, p.z, cx, cz) < 3600 && r.chance(0.3 * dt * 4)) g.fx.emit(cx, top, cz, { count: 1, color: 0x8a8a9a, speed: 0.2, up: 0.9, life: 3, gravity: -0.1, spread: 0.2 }); })(hx, hz, h + 3.2));
      }
      const fx2 = x + sin(ry) * 6 * front, fz2 = z + cos(ry) * 6 * front;
      const px = x + sin(ry) * 8.4 * front, pz = z + cos(ry) * 8.4 * front;
      const road = flatPlane(g, n * 8 + 6, 5, pave, px, pz, 0, 0.012); road.rotation.z = ry;   // a pavement in front of the row
      const f = makeIronFence(n * 8); f.position.set(fx2, 0, fz2); f.rotation.y = ry; W.add(f);
      const lamp = makeLamp('victorian'); lamp.position.set(x + sin(ry) * 8, 0, z + cos(ry) * 8); W.add(lamp); if (lamp.userData.update) U.push(lamp.userData.update);
      P.addBox(x + sin(ry) * 8, 2, z + cos(ry) * 8, 0.4, 4, 0.4, { cam: false });
    } },
    { w: 2, build: (g, r, x, z) => {   // a little cobbled square with market stalls
      flatPlane(g, 22, 22, pave, x, z, 0, 0.015);
      for (const [dx, dz, c] of [[-6, -6, 0xd62839], [6, -6, 0x2f6fd6], [-6, 6, 0x2e9e6e], [6, 6, 0x8a3a8a]]) {
        const s2 = group(x + dx, 0, z + dz, W), wood = mat(0x5a3a1f, { roughness: 1 });
        mesh(G.box(3.2, 0.9, 1.6), mat(0x8a5a32, { roughness: 0.9, map: TEX.planks(28, 32) }), { y: 0.45, parent: s2 });
        for (const [px, pz] of [[-1.5, -0.7], [1.5, -0.7], [-1.5, 0.7], [1.5, 0.7]]) mesh(G.cyl(0.05, 0.05, 2.6, 6), wood, { x: px, y: 1.3, z: pz, parent: s2 });
        for (let i = 0; i < 6; i++) mesh(G.box(0.6, 0.05, 2.2), mat(i % 2 ? c : 0xfff5e6, { roughness: 0.9 }), { x: -1.5 + i * 0.6, y: 2.65, rx: 0.12, parent: s2 });
        P.addBox(x + dx, 0.5, z + dz, 3.2, 1, 1.6, { cam: false });
      }
      const lamp = makeLamp('victorian'); lamp.position.set(x, 0, z); W.add(lamp); if (lamp.userData.update) U.push(lamp.userData.update);
      P.addBox(x, 2, z, 0.4, 4, 0.4, { cam: false });
    } },
    { w: 2, build: (g, r, x, z) => blob(r, x, z, 9, r.int(2, 4), (cx, cz) => addTree(g, r.pick(['oak', 'oak', 'birch']), cx, cz, r)) },
    { w: 1, build: (g, r, x, z) => { makeCarriage(g, x, z, r() * TAU); } },
    { w: 1, build: (g, r, x, z) => { for (const dz of [-5, 5]) { const lamp = makeLamp('victorian'); lamp.position.set(x, 0, z + dz); W.add(lamp); if (lamp.userData.update) U.push(lamp.userData.update); P.addBox(x, 2, z + dz, 0.4, 4, 0.4, { cam: false }); } flatPlane(g, 4, 16, pave, x, z, 0, 0.015); } },
  ] }));
  for (let i = 0; i < 10; i++) {
    const a = r() * TAU, d = r.range(inner, outer * 0.8), x = cos(a) * d, z = sin(a) * d, lady = i % 2 === 1;
    const rig = makeHuman({ ...randomPerson(r, { female: lady }), shirt: r.pick([0x2f2f3a, 0x3d2b4a, 0x4a2b2b, 0x1e2f3f]), pants: 0x1e1e24,
      hat: lady ? 'bonnet' : 'top', hatColor: lady ? r.pick([0x6a3f8a, 0x8a3a3a, 0x2f4f6f]) : 0x0c0c0c,
      coat: !lady, sleeves: lady, dress: lady ? r.pick([0x6a3f8a, 0x8a3a3a, 0x2f4f6f, 0x3a5a3a]) : null, cane: !lady && r.chance(0.6) });
    W.add(rig.group);
    game.npcs.push(new Wanderer(game, rig, { x, z, speed: r.range(0.6, 1.0), leash: 14 }));
  }
}

// ---------------------------------------------------------------- Sunny Shore
function beachRegion(game, U, r, inner, outer) {
  const W = game.world;
  // everything stays on the sand, west of the waterline
  const skip = (x, z) => x > 12;
  U.push(fillRing(game, r, { inner, outer, count: 900, pad: 11, claim: 6, range: 220, skip, kinds: [
    { w: 5, build: (g, r, x, z) => blob(r, x, z, 8, r.int(3, 7), (cx, cz) => { const p = makePalm(r, r.range(3.6, 6.2)); placeT(g, U, p, cx, cz, 0); boxT(g, cx, cz, 0.5, 5, 0.5, { cam: false }); }) },
    { w: 3, build: (g, r, x, z) => makeGrass(g, [[x, z, 13, 130]], r, { hue: [0.13, 0.21], light: [0.4, 0.56], tall: 1.2, wide: 0.85, pad: 0.2 }) },
    { w: 2, build: (g, r, x, z) => blob(r, x, z, 7, r.int(3, 6), (cx, cz) => placeT(g, U, makeRock(r, 0x8a857a, r.range(0.8, 2.2)), cx, cz, 0)) },
    { w: 2, build: (g, r, x, z) => { for (let i = 0; i < r.int(2, 4); i++) { const hx = x + i * 7, hz = z + r.range(-2, 2); placeT(g, U, boxAround(g, makeBeachHut(r.pick([0xff8a65, 0x4fc3f7, 0xfff176, 0x81c784, 0xf48fb1]), r), hx, hz, 2.8, 2.8, 2.8), hx, hz, PI / 2); } } },
    { w: 2, build: (g, r, x, z) => { placeT(g, U, makeUmbrella(r.pick([0, 200, 50, 320, 120])), x, z, 0); boxT(g, x, z, 0.2, 2.2, 0.2, { cam: false }); placeT(g, U, makeTowel(r.pick([0x2f6fd6, 0xff7043, 0x8e24aa, 0x2e9e6e])), x + 1.4, z + 0.8, r() * 0.6); } },
    { w: 1, build: (g, r, x, z) => { placeT(g, U, makeSandcastle(), x, z, r() * TAU); boxT(g, x, z, 1.6, 1.4, 1.6, { cam: false }); } },
    { w: 1, build: (g, r, x, z) => { const l = makeHollowLog(r); l.scale.setScalar(0.8); placeT(g, U, l, x, z, r() * TAU); } },
    { w: 1, build: (g, r, x, z) => makeScatter(g, [[x, z, 9, 40]], G.sphere(0.06, 6, 5), [0xfff1dc, 0xffd9c2, 0xf3e3c8, 0xd9a3a3, 0xe8c9a0], r, [0.6, 1.4], 0.02) },
  ] }));
  for (let i = 0; i < 10; i++) {   // crabs and gulls all the way down the shore
    const z = r.range(-outer * 0.8, outer * 0.8);
    const rig = makeCrab(r.pick([0xe8492b, 0xff7043, 0xc62828])); W.add(rig.group);
    game.npcs.push(new Wanderer(game, rig, { x: r.range(13, 20), z, speed: r.range(0.9, 1.4), leash: 6, r: 0.25, height: 0.5, step: 0.25, idle: [0.5, 2], walk: [1, 3] }));
  }
  for (let i = 0; i < 8; i++) { const rig = makeSeagull({ phase: i * 1.7 }); game.npcs.push(new Flyer(game, rig, { cx: r.range(-30, 16), cz: r.range(-outer * 0.7, outer * 0.7), r: r.range(10, 20), h: r.range(6, 14), speed: r.range(3.5, 5), bob: 1.2, wobble: 3, cw: i % 2 === 0, phase: i })); }
}

// ---------------------------------------------------------------- Frosty Peak
function snowRegion(game, U, r, inner, outer) {
  const W = game.world;
  U.push(fillRing(game, r, { inner, outer, count: 900, pad: 11, claim: 6, range: 180, kinds: [
    { w: 7, build: (g, r, x, z) => blob(r, x, z, 10, r.int(4, 9), (cx, cz) => { const p = makeSnowPine(r); placeT(g, U, p, cx, cz, 0); boxT(g, cx, cz, 1.2 * p.scale.x, 5, 1.2 * p.scale.x, { cam: false }); }) },
    { w: 2, build: (g, r, x, z) => { for (let i = 0; i < r.int(2, 3); i++) { const cx = x + r.range(-7, 7), cz = z + r.range(-7, 7); const c = makeCabin({ wall: r.pick([0x8a5a32, 0x7a4a28, 0x9a6a3a, 0x6a4a2a]), roof: r.pick([0x4a3a30, 0x3a4a5a, 0x5a3a30]), w: r.range(4.5, 5.5), d: r.range(4, 5) }, r); placeT(g, U, c, cx, cz, r() * TAU); const [w, h, d] = c.userData.size; boxT(g, cx, cz, max(w, d) * 0.85, h, max(w, d) * 0.85); } U.push(makeCampfire(g, x, z).userData.update); } },
    { w: 2, build: (g, r, x, z) => { placeT(g, U, makeIgloo(), x, z, r() * TAU); boxT(g, x, z, 3.4, 1.8, 3.4); blob(r, x, z, 7, 2, (cx, cz) => { placeT(g, U, makeSnowman(r), cx, cz, r() * TAU); boxT(g, cx, cz, 1.0, 2.4, 1.0, { cam: false }); }); } },
    { w: 2, build: (g, r, x, z) => blob(r, x, z, 8, r.int(3, 6), (cx, cz) => { const c = makeIceCrystal(r, r.pick([0x9fe8ff, 0xbfa8ff, 0xa8ffe8])); placeT(g, U, c, cx, cz, 0); boxT(g, cx, cz, 0.6, 1.6, 0.6, { cam: false }); }) },
    { w: 2, build: (g, r, x, z) => makeIcePond(g, x, z, r.range(4, 9), r) },
    { w: 2, build: (g, r, x, z) => makeScatter(g, [[x, z, 12, 30]], G.sphere(0.35, 7, 5), [0xffffff, 0xeef3fa, 0xdfe8f2], r, [0.8, 2.2], 0.0) },
    { w: 1, build: (g, r, x, z) => { placeT(g, U, makeSled(r.pick([0xd62839, 0x2f6fd6, 0x2e9e6e])), x, z, r() * TAU); placeT(g, U, makeSnowman(r), x + 2.5, z + 1.5, r() * TAU); boxT(g, x + 2.5, z + 1.5, 1.0, 2.4, 1.0, { cam: false }); } },
  ] }));
  for (let i = 0; i < 10; i++) {
    const a = r() * TAU, d = r.range(inner, outer * 0.8), x = cos(a) * d, z = sin(a) * d;
    if (i % 2) { const rig = makeDeer(); W.add(rig.group); game.npcs.push(new Wanderer(game, rig, { x, z, speed: 0.6, leash: 10, r: 0.45, height: 1.4, step: 0.3, idle: [3, 7], walk: [2, 5] })); }
    else { const rig = makePenguin({ scale: r.range(0.8, 1.05) }); W.add(rig.group); game.npcs.push(new Wanderer(game, rig, { x, z, speed: r.range(0.5, 0.8), leash: 9, r: 0.3, height: 0.9, step: 0.25, idle: [1, 3] })); }
  }
}

// ---------------------------------------------------------------- Whisper Woods
function forestRegion(game, U, r, inner, outer) {
  const W = game.world;
  const bigTree = (g, x, z, o) => { const t = makeBigTree(r, o); placeT(g, U, t, x, z, 0); const [w] = t.userData.col; boxT(g, x, z, w * 0.7, 9, w * 0.7, { cam: false }); return t; };
  U.push(fillRing(game, r, { inner, outer, count: 1100, pad: 9, claim: 5, range: 170, kinds: [
    { w: 8, build: (g, r, x, z) => blob(r, x, z, 11, r.int(3, 7), (cx, cz) => bigTree(g, cx, cz, { simple: r.chance(0.6), lanterns: r.chance(0.12) })) },
    { w: 3, build: (g, r, x, z) => blob(r, x, z, 8, r.int(4, 9), (cx, cz) => { const s = r.range(0.4, 2.6); const m = makeMushroom(s, r.pick([0, 20, 200, 300, 40]), r, r.chance(0.5)); placeT(g, U, m, cx, cz, 0); if (m.userData.update) U.push(m.userData.update); if (s > 1.4) boxT(g, cx, cz, 0.5 * s, 1.3 * s, 0.5 * s, { cam: false }); }) },
    { w: 3, build: (g, r, x, z) => makeFerns(g, [[x, z, 14, 40]], r) },
    { w: 2, build: (g, r, x, z) => blob(r, x, z, 6, r.int(2, 4), (cx, cz) => { placeT(g, U, makeStump(r), cx, cz, r() * TAU); boxT(g, cx, cz, 1.0, 0.75, 1.0, { cam: false }); }) },
    { w: 2, build: (g, r, x, z) => { placeT(g, U, makeHollowLog(r), x, z, r() * TAU); boxT(g, x, z, 1.4, 1.2, 1.4, { cam: false }); } },
    { w: 2, build: (g, r, x, z) => blob(r, x, z, 7, r.int(2, 5), (cx, cz) => placeT(g, U, makeRock(r, 0x6b7a6a, r.range(1.0, 2.4)), cx, cz, 0)) },
    { w: 1, build: (g, r, x, z) => { U.push(makeGlowPond(g, x, z, r.range(3.5, 6), r).userData.update); blob(r, x, z, 9, 8, (cx, cz) => { const m = makeMushroom(r.range(0.4, 0.8), r.pick([0, 300, 200]), r, true); placeT(g, U, m, cx, cz, 0); if (m.userData.update) U.push(m.userData.update); }); } },
    { w: 1, build: (g, r, x, z) => { const a = r() * TAU, bx = x + cos(a) * 16, bz = z + sin(a) * 16; bigTree(g, x, z, { lanterns: true }); bigTree(g, bx, bz, { lanterns: true }); U.push(makeLanternString(g, x, z, bx, bz, 7, 4.2).update); } },
  ] }));
  for (let i = 0; i < 14; i++) {
    const a = r() * TAU, d = r.range(inner, outer * 0.85), x = cos(a) * d, z = sin(a) * d;
    if (i % 3 === 0) { const rig = makeDeer(); W.add(rig.group); game.npcs.push(new Wanderer(game, rig, { x, z, speed: 0.6, leash: 11, r: 0.45, height: 1.4, step: 0.3, idle: [3, 7], walk: [2, 5] })); }
    else if (i % 3 === 1) { const rig = makeFox(); W.add(rig.group); game.npcs.push(new Wanderer(game, rig, { x, z, speed: 1.3, leash: 12, r: 0.3, height: 0.8, step: 0.3, idle: [1, 3], walk: [2, 5] })); }
    else { const rig = makeButterfly(r.pick([300, 40, 200, 20, 260])); game.npcs.push(new Flyer(game, rig, { cx: x, cz: z, r: r.range(2, 5), h: r.range(0.8, 2.4), speed: r.range(0.8, 1.6), bob: 0.3, wobble: 0.8, cw: i % 2 === 0 })); }
  }
}
